### ISSUE TITLE
#10 Passing function call information to another instance

### ISSUE THREAD

**Issue by zzttt** [hoonkim/rune#10]
1. Might have to define how to inform function calls from users.
   - I'll send this information to @hoonkim 
2. Need to get information from @TaeyoungJang 's API gateway

**Comment by zzttt** [comment]
Function call would be sent through RabbitMQ so I ask @hoonkim to make a queue to receive mine.

I'm going to test a sample practice and inform you of the result

**Comment by hoonkim** [comment]
So, @zzttt  all instances would have their own Queue? or just gonna use Queue of Openstack?

**Comment by zzttt** [comment]
all instances you manage.  I think you might have to make a few instances which have rabbitMQ and one of my instances is going to send msg to yours . just let me know what the instances you use(address of the instances on OpenStack).

**Comment by teo-jang** [comment]
case of HTTP:

refer below links: 
[RuneHTTP merged](https://github.com/hoonkim/rune/commit/6100106d51e9dcdcafc149667f2938821e9145d8)

both you can import this library and implement additional function also. 

case of RabbitMQ:
 I think @hoonkim will submit special, powerful library for using rabbitMQ to US :^)

**Comment by hoonkim** [comment]
# Function Call Example.

`{
    "user" : "kim",
    "project" : "rune",
    "function" : "getTime",
    "params" : [
        "seoul", "kr", "nano"
    ],
    "validate" : true
}`

**Comment by teo-jang** [comment]
[check it](https://github.com/hoonkim/rune/commit/dcf21ff1408519b2961ce07ec3a5a264b8471224) @hoonkim

**Comment by hoonkim** [comment]
@TaeyoungJang 
checking what?

**Comment by zzttt** [comment]
@hoonkim  will send function's result to @TaeyoungJang  through ResponseFunctionCall which I pass on the argument of call method in wisp_monitor

the result data might have to be a dictionary type ( type check was implemented by @TaeyoungJang )
so I suggest that @hoonkim make a dictionary type JSON data for the result

**Comment by teo-jang** [comment]
@zzttt 
Response is received should be contained execution time of functions.

**Comment by zzttt** [comment]
@TaeyoungJang 
Resource state of instances and execution time will be sent on a response when the function call 's requested

plz inform if this logic has any issues
