### ISSUE TITLE
#12 How to install docker

### ISSUE THREAD

**Issue by seok0721** [hoonkim/rune#12]
# Guide
- Link: https://docs.docker.com/engine/installation/linux/ubuntulinux
- Please to follow prerequisites & Install section.
- After install docker, I recommend to type below step:
  
  $ docker pull ubuntu # Pull ubuntu docker image of all version from docker-hub.
  $ docker run -i -t --name=rune --rm ubuntu /bin/bash #  Create run-and-destroy container that has named rune.

**Comment by teo-jang** [comment]
You can use wiki page for this article with below link:
[Rune Wiki](https://github.com/hoonkim/rune/wiki)

Do not write article in Issue page.
