### ISSUE TITLE
Client's Source code manager should be implemeneted.

### ISSUE THREAD

**Issue by hoonkim** [hoonkim/rune#13]
I need a client's source code manager which satisfying  following requirements.
# **Requirements:**

**mandatory**
1. If I request a "function" with client's id, project name and function name, copy the source code of the "function" from block storage or object storage to instance.
1. Returns it's absolute path under instance's space.

**optional**
- Instance's storage space is limited. So it would be nice if source files have their own life cycle.(like LFU algorithm)

*\* Assign to.. **
@seok0721 : We need a storage to keep client's source code.
@Songkey1 : Dashboard will save source code on the storage.
@zzttt : Implement above. Please use Wisp branch or branch out from wisp.

**Comment by zzttt** [comment]
Now I'm making an environment for it on openstack  (my laptop)

**Comment by seok0721** [comment]
@zzttt My goal is to create instance using openstack with docker. Currently, I installed openstack components successful such as keystone, glance, nova and neutron in my labtop, and verified my auto installing scripts. But I failed to install nova-docker. zzttt, could you tell me how to test openstack, kvm or etc?

**Comment by zzttt** [comment]
@seok0721  I don't know the meaning of testing openstack :(. What test do you mean ?

**Comment by seok0721** [comment]
@zzttt Oh, I mean that test is collecting data(network traffic, cpu usage) and sending data to @TaeyoungJang inside of instance. As you know, openstack has a method for creating instance(docker, kvm, lxc), so just I want to know your next step after install openstack :)
