### ISSUE TITLE
개발 전 협의할 점들

### ISSUE THREAD

**Issue by Songkey1** [hoonkim/rune#4]
@TaeyoungJang , @hoonkim , @zzttt 
이슈 앞에다가 [번호] 주내용 으로 제목을 적고
브랜치는 이름/번호로 합시다. 반박하려면 댓글다셈.

커밋에다가는 첫줄에
[번호] 주내용 그대로 적고
그다음 줄에 이슈로 가는 url 적기
그밑에 해당 이슈에 관련된 개발 내용 적으면 좋을 듯.

풀리퀘는 보내고 신랄하게 반박해도 울기없기.

할 말은 댓글로 해보셈 연습좀하게 ㅋ

**Comment by zzttt** [comment]
Yes

**Comment by hoonkim** [comment]
@Songkey1 
번호가 뭐야 #5
아.. 이렇게하면 이슈 링크가 걸리는구나

**Comment by Songkey1** [comment]
when commit without issue, then start with [no-number] title,
ex) [no-number] prototype source add
first commit
