### ISSUE TITLE
Defined Role

### ISSUE THREAD

**Issue by zzttt** [hoonkim/rune#5]
1. @Songkey1
2. @hoonkim 
3. @zzttt
4. @seok0721 
5. @TaeyoungJang

**Comment by seok0721** [comment]
저 @왕석 대신에  @seok0721 로 사용할게욥

**Comment by teo-jang** [comment]
we should make synonym dictionary

https://github.com/hoonkim/rune/wiki/Synonym---Definition-for--our-words

write our own words for information
