### ISSUE TITLE
Console?

### ISSUE THREAD

**Issue by hoonkim** [hoonkim/rune#7]
Will we provide console?
Unless, to where stdout of lambda will print out?

**Comment by teo-jang** [comment]
Decide it supports stdin or not. maybe it required some argument for process. 
- if it will support stdin, we should find the way for mapping stdin (or similar process for make stdin)
  - select one of type: real time console or not.
- if it won't support stdin, we don't need make any decision.

Stdout mapping is not difficult issue than stdin. first of all, decide support stdin or not

**Comment by hoonkim** [comment]
@TaeyoungJang 
I'm not considering stdin, and all functions using stdin will throw an exception.
so no stdin

**Comment by hoonkim** [comment]
Ok, I'm closing this issue, and concluding that we don't have console, but I'm gonna consider other options to handle STDOUT

**Comment by hoonkim** [comment]
Ok, I'm closing this issue, and concluding that we don't have console, but I'm gonna consider other options to handle STDOUT
