### ISSUE TITLE
regular information form ( from client to server )

### ISSUE THREAD

**Issue by teo-jang** [hoonkim/rune#8]
@zzttt archtiect and implement with me
- regular status
  - server id
  - server status(default)
  - work status(default)
- server status 
  - default:
    CPU Usage -  (xx% used)
    Memory Usage - (xx% used)
    I/O Status - (network, dist r/w status)
  - detail (request / per request):
    - CPU Usage
      - user
      - sys
      - idle
    - Memory usage
      - total size
      - used size
    - Process list
      - running
      - stuck
      - sleeping
      - thread num
        -Processes
        - our Processes 
          (include Summary)
          - PID
          - Thread num
          - cpu usage
          - memory usage
        - not our Processes
          (include Summary)
          - PID
          - Thread num
          - cpu usage
          - memory usage
    - I/O Status
      - Network In / Out
      - Disk Read / Write
- work status
  - default: 
    - current process queue (start at - )
    - remain  function process queue
    - average function process time
  - detail:
    - function resolve history ( last xxx works )
    - expected resolve remain queue works
    - function binary status (list)
      - binary idx
      - binary date

**Comment by zzttt** [comment]
I should run 2 instances to implement logic for it 
First instance is a monitor to send status of another instance to @TaeyoungJang's process.
The another instance is the test instance to be checked instance's status by first instance.

**Comment by teo-jang** [comment]
[check it](https://github.com/hoonkim/rune/commit/dcf21ff1408519b2961ce07ec3a5a264b8471224) @zzttt

**Comment by zzttt** [comment]
job done
